### ISSUE TITLE
Compatibility with SparkFun RedBoard

### ISSUE THREAD

**Issue by pzula** [hybridgroup/gort#24]
I assume this issue is linked to another issue (https://github.com/hybridgroup/gort/issues/21) that reports the inability to use a different 'style' of Arduino board. I have a bunch of RedBoards by SparkFun (which are Arduino compatible) that I am unable to use gort with in order to upload the Arduino firmata. When I try to run `./gort arduino upload /dev/tty.usbserial-A702MX5M`, this is the output I receive:

```
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x2e58a0, 0x4e031c)
	/home/adrian/go/go_1.3.1/src/pkg/runtime/panic.c:279 +0xf5
github.com/hybridgroup/gort/commands.func·002(0x20859e210)
	/home/adrian/development/gopath/src/github.com/hybridgroup/gort/commands/arduino.go:90 +0x1996
github.com/codegangsta/cli.Command.Run(0x329970, 0x7, 0x0, 0x0, 0x389230, 0x35, 0x0, 0x0, 0x0, 0x0, ...)
	/home/adrian/development/gopath/src/github.com/codegangsta/cli/command.go:101 +0xc6f
github.com/codegangsta/cli.(*App).Run(0x2085aa0c0, 0x208564000, 0x4, 0x4, 0x0, 0x0)
	/home/adrian/development/gopath/src/github.com/codegangsta/cli/app.go:125 +0x941
main.main()
	/home/adrian/development/gopath/src/github.com/hybridgroup/gort/gort.go:23 +0x27f

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
	/home/adrian/go/go_1.3.1/src/pkg/runtime/mheap.c:507
runtime.goexit()
	/home/adrian/go/go_1.3.1/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
	/home/adrian/go/go_1.3.1/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
	/home/adrian/go/go_1.3.1/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
	/home/adrian/go/go_1.3.1/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
	/home/adrian/go/go_1.3.1/src/pkg/runtime/proc.c:1445
```

I'm not too familiar with go, but I did poke around in the source, and it seems to be occurring on this line: https://github.com/hybridgroup/gort/blob/master/commands/arduino.go#L20

I'm here at RobotsConf, so if anyone wants to work together to debug this, I'd love to help get RedBoards working with gort!

**Comment by X1ting** [comment]
have same trouble
